import type { NextPage } from "next";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiOutlineArrowUp,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>----------Portofolio----------</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-30">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Bonsoir</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-green-800 to-green-700 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center md:p-10">
            <h2 className="text-5xl text-green-800 font-bold py-2">
              Alexandre Bourguignon
            </h2>
            <h3 className="text-2xl font-medium">Developpeur</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatum commodi necessitatibus facilis iure laborum fugiat
              voluptate animi. Quis suscipit minima dolor quia laudantium
              accusamus consequuntur tempore repellendus. Autem, fugit? Aperiam
              accusamus expedita ab facere adipisci tenetur rerum placeat labore
              asperiores! Sequi ea blanditiis autem iure accusamus expedita
              minima tempora animi.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-20 md:gap-60 md:text-7xl py-3 text-gray-500">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer :</h3>
            <p>Since the beginning of my journey as a freelance</p>
          </div>
        </section>
        <button className="fixed h-10 w-10 bottom-10 right-10 bg-gradient-to-br from-green-800 to-green-500 rounded-full flex items-center justify-center">
          <a href="#" className=" text-center text-white text-2xl">
            <AiOutlineArrowUp />
          </a>
        </button>
      </main>
    </>
  );
};

export default Home;
